version: "3.9"
services:
  blog-drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres:17.0-bullseye
    environment:
      - POSTGRES_USER_FILE=/dbuser
      - POSTGRES_PASSWORD_FILE=/dbpass
      - POSTGRES_DB=DefaultDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dbuser:/dbuser
      - ./dbpass:/dbpass


volumes:
  drupal-profiles:
    external: true
  drupal-sites:
    external: true
  postgres_data:
    external: true
