version: "3.9"
services:
  blog-drupal:
    image: rulyotano/drupal-11:0.0.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.http.services.blog.loadbalancer.server.port=80"
        - "traefik.http.routers.blog.rule=Host(`blog.rulyotano.com`)"
        - "traefik.http.routers.blog.tls=true"
        - "traefik.http.routers.blog.tls.certresolver=mycertresolver"
        - "traefik.http.routers.blog.middlewares=blogratelimit"
        - "traefik.http.routers.bloghttp.rule=Host(`blog.rulyotano.com`)"
        - "traefik.http.routers.bloghttp.middlewares=redirecthttps,blogratelimit"
        - "traefik.http.middlewares.blogratelimit.ratelimit.average=100"
        - "traefik.http.middlewares.blogratelimit.ratelimit.burst=50"
    networks:
      - traefik
      - backend
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

networks:
  traefik:
    external: true
  backend:
    external: true

volumes:
  drupal-modules:
    external: true
  drupal-profiles:
    external: true
  drupal-sites:
    external: true
  drupal-themes:
    external: true