version: "3.9"
services:
  blog-drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - drupal-sites:/var/www/html/sites

  postgres:
    image: postgres:17.0-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  drupal-sites:
    external: true
  postgres_data:
    external: true
