name: Deploy Blog

on: 
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Ssh connect and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: |
            wget https://raw.githubusercontent.com/rulyotano/rulyotano.blog/main/docker-compose.production.yml -O docker-compose.yml
            docker stack deploy -c docker-compose.yml blog
            rm docker-compose.*
    
